# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: MikeTheTech.VirtualDisplayDriver
PackageVersion: 25.7.23
PackageLocale: en-US
Publisher: MikeTheTech
PackageName: Virtual Display Driver
License: MIT
ShortDescription: This project creates a virtual monitor in Windows that functions just like a physical display
ManifestType: defaultLocale
ManifestVersion: 1.10.0
